
name: 'jaffle_shop'
version: '0.2'
profile: 'jaffle_shop'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["raw"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      materialized: view
      marts:
        materialized: table
        
seeds:
  # https://docs.getdbt.com/reference/seed-configs
  +quote_columns: true
  jaffle_shop:
    +enabled: true
    +schema: raw
